#!/bin/bash -e
#
# gitl-prompt
#
# https://github.com/lennartcl/gitl
#
# License: MIT
# Copyright (c) 2012 Lennart C. L. Kats

PROMPT='  PS1='\''\[\033[01;32m\]\u:\[\033[01;34m\]$(pwd | sed "s|$HOME|~|")\[\033[0;36m\]$(git-get-branch -p)\[\033[00m\]\$ '\'


echo "Add this to the .bashrc or .profile in your home directory:"
echo
echo $PROMPT
