#!/bin/bash -e
#
# git-push-branch
#
# License: MIT
# Copyright (c) 2012 Lennart C. L. Kats

OPTIONS=
while [ $# != 0 ]; do
  if echo $1 | grep '^-' > /dev/null; then
    OPTIONS="$OPTIONS $1"
    shift
  else
    sh -c "git push origin $OPTIONS $*"
    exit
  fi
done

if [ $# == 0 ]; then
  sh -c "git push $OPTIONS origin `git-get-branch`"
fi
