#!/bin/bash -e

OPTIONS=
while [ $# != 0 ]; do
  if echo $1 | grep '^-' > /dev/null; then
    OPTIONS="$OPTIONS $1"
    shift
  else
    sh -c "git pull origin $OPTIONS $*"
    exit
  fi
done

if [ $# == 0 ]; then
  sh -c "git pull $OPTIONS origin `git-get-branch`"
fi
