#!/bin/bash -e
#
# git-info
#
# License: MIT
# Copyright (c) 2012 Lennart C. L. Kats

WEB=
if [ "$1" == "-w" ]; then
  WEB=-w
  shift
fi

REV=
if [ "$1" != "" ] && git rev-parse $1 &>/dev/null; then
  REV=$1
  shift
elif [ "$1" == "-r" ]; then
  REV=$2
  shift; shift
fi

if [ "$1" == "-w" ]; then
  WEB=-w
  shift
fi

if [ "$1" == "" ]; then
  FILE=
elif [ -d "$1" ]; then
  cd "$1"
  FILE=
else
  echo nop
  FILE="$1"
fi

if ! git remote &>/dev/null; then
  cd `dirname "$FILE"`
  FILE="`basename "$FILE"`"
fi

REMOTE=`git remote -v | grep 'origin.*push' | grep -oE 'github.com[:/][^/]+/[^\.]+'` ||
(echo 'No remote for current directory' >&2 && exit 1)

if [ ! $REMOTE ]; then
  echo Repository not recognized:
  git remote -v
  exit 1
fi

USER=`echo $REMOTE | perl -pe 's|github.com.([^/]+)/.*|$1|'`
REPO=`echo $REMOTE | perl -pe 's|github.com.[^/]+/(.*)|$1|'`
BRANCH=`git-get-branch 2>/dev/null || git rev-parse HEAD`

FILE=`cd -P -- "$(dirname -- "$FILE")" && echo "$(pwd -P)/$(basename -- "$FILE")"`
while [ ! -e .git ] && [ "`pwd`" != "/" ]; do
  cd ..
done
BASEPATH=`ls -d $(pwd)`
RELPATH=`echo "$FILE" | sed "s|$BASEPATH/||"`

if [ -d "$FILE" ]; then
  FILE=
else
  git status "$FILE"
fi

if [ $REV ] && [ ! $FILE ]; then
  URL="https://github.com/$USER/$REPO/commit/$REV"
elif [ $REV ]; then
  URL="https://github.com/$USER/$REPO/blob/$REV/$RELPATH"
else
  URL="https://github.com/$USER/$REPO/blob/$BRANCH/$RELPATH"
fi

echo "# URL:"
echo $URL

if [ $WEB ]; then
  open $URL
fi
