#!/bin/bash -e
#
# gitl-setup
#
# https://github.com/lennartcl/gitl
#
# License: MIT
# Copyright (c) 2012 Lennart C. L. Kats

echo -n "github username: "
read NAME
echo -n "Logging in to github. "
RESPONSE=`curl -s -u $NAME -d '{"scopes":["user","public_repo","repo","gist"],"note":"gitl","note_url":"https://github.com/lennartcl/gitl"}' https://api.github.com/authorizations`

if echo $RESPONSE | grep -o "Bad credentials" >&2; then
  exit 1
fi

TOKEN=`echo $RESPONSE | perl -pe 's/.*token"?\s*:\s*"([^"]*)".*.*/$1/'`

# TODO: print what should be in .profile; check for PATH setting
#       maybe suggest bash completions, based on which git or locate
echo
echo Application registered at https://github.com/settings/applications/.
echo
echo Please add the following to the .profile file in your home directory:
echo
echo   export GITHUB_USER=$NAME
echo   export GITHUB_TOKEN=$TOKEN
echo "  # For git-list-pull-requests, please add the repositories"
echo "  # you'd like to include to GITHUB_REPOS, separated by spaces."
echo "  # Optionally, specify a local file system path using a colon, e.g."
echo '  # GITHUB_REPOS="lennartcl/gitl:~/projects/gitl ajaxorg/cloud9:~/projects/cloud9'
echo '  export GITHUB_REPOS='
if ! which git-l &>/dev/null; then
  echo PATH=\$PATH:`cd $(dirname $0); pwd`
fi
echo
echo Additionally, to change your prompt, add something like:
echo
echo '  PS1='\''\[\033[01;32m\]\u:\[\033[01;34m\]$(pwd | sed "s|$HOME|~|")\[\033[0;36m\]$(git-get-branch -p)\[\033[00m\]\$ '\'
